// Mocks generated by Mockito 5.4.4 from annotations
// in dutch_app/test/word_collections/word_collections_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i12;

import 'package:dutch_app/core/io/v1/models/export_package_v1.dart' as _i9;
import 'package:dutch_app/core/local_db/repositories/batch_repository.dart'
    as _i4;
import 'package:dutch_app/core/local_db/repositories/word_collections_repository.dart'
    as _i5;
import 'package:dutch_app/core/local_db/repositories/words_import_repository.dart'
    as _i3;
import 'package:dutch_app/domain/models/new_word_collection.dart' as _i7;
import 'package:dutch_app/domain/models/word_collection.dart' as _i2;
import 'package:dutch_app/domain/services/batch_word_operations_service.dart'
    as _i8;
import 'package:dutch_app/pages/quick_practice/quick_practice_coordinator.dart'
    as _i10;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWordCollection_0 extends _i1.SmartFake
    implements _i2.WordCollection {
  _FakeWordCollection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWordsImportRepository_1 extends _i1.SmartFake
    implements _i3.WordsImportRepository {
  _FakeWordsImportRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBatchRepository_2 extends _i1.SmartFake
    implements _i4.BatchRepository {
  _FakeBatchRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WordCollectionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordCollectionsRepository extends _i1.Mock
    implements _i5.WordCollectionsRepository {
  MockWordCollectionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<int> addAsync(_i7.NewWordCollection? wordCollection) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAsync,
          [wordCollection],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i2.WordCollection>> getAsync() => (super.noSuchMethod(
        Invocation.method(
          #getAsync,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.WordCollection>>.value(<_i2.WordCollection>[]),
      ) as _i6.Future<List<_i2.WordCollection>>);

  @override
  _i6.Future<_i2.WordCollection> getCollectionWithWordsAsync(
          int? collectionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionWithWordsAsync,
          [collectionId],
        ),
        returnValue: _i6.Future<_i2.WordCollection>.value(_FakeWordCollection_0(
          this,
          Invocation.method(
            #getCollectionWithWordsAsync,
            [collectionId],
          ),
        )),
      ) as _i6.Future<_i2.WordCollection>);

  @override
  _i6.Future<List<_i2.WordCollection>> getCollectionsWithWordsAsync() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionsWithWordsAsync,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.WordCollection>>.value(<_i2.WordCollection>[]),
      ) as _i6.Future<List<_i2.WordCollection>>);

  @override
  _i6.Future<bool> updateAsync(_i2.WordCollection? updatedCollection) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAsync,
          [updatedCollection],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [BatchWordOperationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatchWordOperationsService extends _i1.Mock
    implements _i8.BatchWordOperationsService {
  MockBatchWordOperationsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WordsImportRepository get importRepository => (super.noSuchMethod(
        Invocation.getter(#importRepository),
        returnValue: _FakeWordsImportRepository_1(
          this,
          Invocation.getter(#importRepository),
        ),
      ) as _i3.WordsImportRepository);

  @override
  _i4.BatchRepository get batchRepository => (super.noSuchMethod(
        Invocation.getter(#batchRepository),
        returnValue: _FakeBatchRepository_2(
          this,
          Invocation.getter(#batchRepository),
        ),
      ) as _i4.BatchRepository);

  @override
  _i6.Future<void> storeInDatabaseAsync(_i9.ExportPackageV1? package) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeInDatabaseAsync,
          [package],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAsync({
    required List<int>? wordIds,
    required List<int>? collectionIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAsync,
          [],
          {
            #wordIds: wordIds,
            #collectionIds: collectionIds,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [QuickPracticeCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuickPracticeCoordinator extends _i1.Mock
    implements _i10.QuickPracticeCoordinator {
  MockQuickPracticeCoordinator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> startAsync(_i11.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAsync,
          [context],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
