// Mocks generated by Mockito 5.4.4 from annotations
// in dutch_app/test/session/word_progress_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dutch_app/core/local_db/entities/db_word_progress.dart' as _i6;
import 'package:dutch_app/core/local_db/repositories/tools/word_progress_key.dart'
    as _i5;
import 'package:dutch_app/core/local_db/repositories/word_progress_batch_repository.dart'
    as _i3;
import 'package:dutch_app/core/local_db/repositories/word_progress_repository.dart'
    as _i2;
import 'package:dutch_app/domain/types/exercise_type_detailed.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWordProgressRepository_0 extends _i1.SmartFake
    implements _i2.WordProgressRepository {
  _FakeWordProgressRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WordProgressBatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordProgressBatchRepository extends _i1.Mock
    implements _i3.WordProgressBatchRepository {
  MockWordProgressBatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WordProgressRepository get wordProgressRepository => (super.noSuchMethod(
        Invocation.getter(#wordProgressRepository),
        returnValue: _FakeWordProgressRepository_0(
          this,
          Invocation.getter(#wordProgressRepository),
        ),
      ) as _i2.WordProgressRepository);

  @override
  _i4.Future<Map<_i5.WordProgressKey, _i6.DbWordProgress>> getOrCreateManyAsync(
          List<_i5.WordProgressKey>? keys) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateManyAsync,
          [keys],
        ),
        returnValue:
            _i4.Future<Map<_i5.WordProgressKey, _i6.DbWordProgress>>.value(
                <_i5.WordProgressKey, _i6.DbWordProgress>{}),
      ) as _i4.Future<Map<_i5.WordProgressKey, _i6.DbWordProgress>>);

  @override
  _i4.Future<void> saveAllAsync(List<_i6.DbWordProgress>? progressList) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAllAsync,
          [progressList],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.DbWordProgress>> getProgressForWordsAsync(
          List<int>? wordIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgressForWordsAsync,
          [wordIds],
        ),
        returnValue:
            _i4.Future<List<_i6.DbWordProgress>>.value(<_i6.DbWordProgress>[]),
      ) as _i4.Future<List<_i6.DbWordProgress>>);

  @override
  _i4.Future<List<_i6.DbWordProgress>> getDueProgressAsync(
    _i7.ExerciseTypeDetailed? exerciseType,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDueProgressAsync,
          [
            exerciseType,
            limit,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.DbWordProgress>>.value(<_i6.DbWordProgress>[]),
      ) as _i4.Future<List<_i6.DbWordProgress>>);

  @override
  _i4.Future<List<_i6.DbWordProgress>> getTomorrowProgressAsync(
    _i7.ExerciseTypeDetailed? exerciseType,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTomorrowProgressAsync,
          [
            exerciseType,
            limit,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.DbWordProgress>>.value(<_i6.DbWordProgress>[]),
      ) as _i4.Future<List<_i6.DbWordProgress>>);

  @override
  _i4.Future<List<_i6.DbWordProgress>> getRecentlyLearnedProgressAsync(
    _i7.ExerciseTypeDetailed? exerciseType,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentlyLearnedProgressAsync,
          [
            exerciseType,
            limit,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.DbWordProgress>>.value(<_i6.DbWordProgress>[]),
      ) as _i4.Future<List<_i6.DbWordProgress>>);

  @override
  _i4.Future<List<_i6.DbWordProgress>> getRandomProgressAsync(
    _i7.ExerciseTypeDetailed? exerciseType,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomProgressAsync,
          [
            exerciseType,
            limit,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.DbWordProgress>>.value(<_i6.DbWordProgress>[]),
      ) as _i4.Future<List<_i6.DbWordProgress>>);

  @override
  _i4.Future<List<_i6.DbWordProgress>> getWeakestProgressAsync(
    _i7.ExerciseTypeDetailed? exerciseType,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeakestProgressAsync,
          [
            exerciseType,
            limit,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.DbWordProgress>>.value(<_i6.DbWordProgress>[]),
      ) as _i4.Future<List<_i6.DbWordProgress>>);

  @override
  _i4.Future<bool> practicedTodayExistsAsync() => (super.noSuchMethod(
        Invocation.method(
          #practicedTodayExistsAsync,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
